// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yeliadnisbpmhikprqxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllbGlhZG5pc2JwbWhpa3BycXh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4OTczOTMsImV4cCI6MjA1ODQ3MzM5M30.-1Z-hvgcdRp6HrO9NSI9-nN0ZoU7DapSWpasP4JMKto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);