// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxabsvmrhweeqhwexzpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4YWJzdm1yaHdlZXFod2V4enB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NTMzNjIsImV4cCI6MjA1ODEyOTM2Mn0.1AP2zR7H4Ti9g0jD6zJJwqCaeWJyZJ4T8Zagts0V5mI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);